
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    generate-ddl: off
    database: mysql

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  devtools:
    livereload:
      enabled: true

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/boardproject?characterEncoding=UTF-8
    username: root
    password: 1234


server:
  port: 9095

logging:
  file:
    path: logback-spring
