spring:
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 3000
  tomcat:
    max-swallow-size: -1

logging:
  file:
    path: logback-spring